export const TradingABI = {
  abi: [
    {
      inputs: [
        { internalType: "address", name: "_initialOwner", type: "address" },
        { internalType: "address", name: "_evvmAddress", type: "address" },
        { internalType: "address", name: "_treasuryAddress", type: "address" },
        {
          internalType: "address",
          name: "_nameServiceAddress",
          type: "address",
        },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    { inputs: [], name: "AlreadyInitialized", type: "error" },
    {
      inputs: [
        { internalType: "uint256", name: "have", type: "uint256" },
        { internalType: "uint256", name: "want", type: "uint256" },
      ],
      name: "CANT_WITHDRAW_MORE_THAN_ACCOUNT_HAVE",
      type: "error",
    },
    { inputs: [], name: "INVALID_SIGNATURE", type: "error" },
    { inputs: [], name: "InvalidAddress", type: "error" },
    { inputs: [], name: "InvalidCaip10Format", type: "error" },
    { inputs: [], name: "NONCE_ALREADY_USED", type: "error" },
    { inputs: [], name: "NewOwnerIsZeroAddress", type: "error" },
    { inputs: [], name: "NoHandoverRequest", type: "error" },
    { inputs: [], name: "NotEvmChain", type: "error" },
    { inputs: [], name: "StringsInvalidAddressFormat", type: "error" },
    { inputs: [], name: "Unauthorized", type: "error" },
    {
      inputs: [{ internalType: "address", name: "owner", type: "address" }],
      name: "YOURE_NOT_THE_OWNER_OF_THE_ACCOUNT",
      type: "error",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "string",
          name: "caip10Wallet",
          type: "string",
        },
        {
          indexed: false,
          internalType: "string",
          name: "caip10Token",
          type: "string",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "address",
          name: "evmDepositorAddress",
          type: "address",
        },
      ],
      name: "Deposit",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "executor",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "user",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "reward",
          type: "uint256",
        },
      ],
      name: "ExecutorRewarded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "string",
          name: "caip10Wallet",
          type: "string",
        },
        {
          indexed: false,
          internalType: "string",
          name: "caip10Token",
          type: "string",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "feeAmount",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "bool",
          name: "isStaker",
          type: "bool",
        },
      ],
      name: "FeeCollected",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          components: [
            { internalType: "string", name: "caip10Wallet", type: "string" },
            { internalType: "string", name: "caip10Token", type: "string" },
            {
              internalType: "address",
              name: "evmDepositorWallet",
              type: "address",
            },
            { internalType: "uint256", name: "newAmount", type: "uint256" },
          ],
          indexed: false,
          internalType: "struct Trading.SyncUpArguments[]",
          name: "newInfo",
          type: "tuple[]",
        },
      ],
      name: "NewSyncUp",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "string",
          name: "caip10Wallet",
          type: "string",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "nonce",
          type: "uint256",
        },
      ],
      name: "OrderCancelled",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "pendingOwner",
          type: "address",
        },
      ],
      name: "OwnershipHandoverCanceled",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "pendingOwner",
          type: "address",
        },
      ],
      name: "OwnershipHandoverRequested",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "oldOwner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "newOwner",
          type: "address",
        },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "string",
          name: "caip10Wallet",
          type: "string",
        },
        {
          indexed: false,
          internalType: "string",
          name: "caip10Token",
          type: "string",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "address",
          name: "evmDepositorAddress",
          type: "address",
        },
      ],
      name: "Withdraw",
      type: "event",
    },
    {
      inputs: [],
      name: "BASIS_POINTS_DIVISOR",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "EXECUTOR_REWARD_PERCENT",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "FEE_BASIS_POINTS",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "STAKER_DISCOUNT_PERCENT",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "string", name: "_caip10Wallet", type: "string" },
        { internalType: "uint256", name: "_nonce", type: "uint256" },
        { internalType: "bytes", name: "_signature", type: "bytes" },
      ],
      name: "cancelOrder",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "cancelOwnershipHandover",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "pendingOwner", type: "address" },
      ],
      name: "completeOwnershipHandover",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "string", name: "_caip10Token", type: "string" },
        { internalType: "string", name: "_caip10Wallet", type: "string" },
        { internalType: "uint256", name: "_amount", type: "uint256" },
        {
          internalType: "enum Trading.ActionIs",
          name: "_action",
          type: "uint8",
        },
        {
          internalType: "string",
          name: "_depositorWalletOrName",
          type: "string",
        },
      ],
      name: "deposit",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "string", name: "caip10Wallet", type: "string" },
        { internalType: "string", name: "caip10Token", type: "string" },
      ],
      name: "depositorInfo",
      outputs: [
        {
          internalType: "address",
          name: "evmDepositorWallet",
          type: "address",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "evvmAddress",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "user", type: "address" },
        { internalType: "uint256", name: "nonce", type: "uint256" },
      ],
      name: "executorNonces",
      outputs: [{ internalType: "bool", name: "used", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "string", name: "_caip10Wallet", type: "string" },
        { internalType: "string", name: "_caip10Token", type: "string" },
      ],
      name: "getDepositor",
      outputs: [
        { internalType: "address", name: "depositor", type: "address" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_amount", type: "uint256" },
        { internalType: "string", name: "_caip10Wallet", type: "string" },
        { internalType: "string", name: "_caip10Token", type: "string" },
      ],
      name: "getFeeInfo",
      outputs: [
        { internalType: "uint256", name: "fee", type: "uint256" },
        { internalType: "uint256", name: "netAmount", type: "uint256" },
        { internalType: "bool", name: "isStaker", type: "bool" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "string", name: "_caip10Wallet", type: "string" },
        { internalType: "string", name: "_caip10Token", type: "string" },
      ],
      name: "getTradeBalance",
      outputs: [{ internalType: "uint256", name: "balance", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "nameServiceAddress",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "string", name: "caip10Wallet", type: "string" },
        { internalType: "uint256", name: "nonce", type: "uint256" },
      ],
      name: "orderNonces",
      outputs: [{ internalType: "bool", name: "used", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "result", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "pendingOwner", type: "address" },
      ],
      name: "ownershipHandoverExpiresAt",
      outputs: [{ internalType: "uint256", name: "result", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "_addressStr", type: "string" }],
      name: "parseAddressExternal",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "pure",
      type: "function",
    },
    {
      inputs: [],
      name: "renounceOwnership",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [],
      name: "requestOwnershipHandover",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "setOwnerForTesting",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        {
          components: [
            { internalType: "string", name: "caip10Wallet", type: "string" },
            { internalType: "string", name: "caip10Token", type: "string" },
            {
              internalType: "address",
              name: "evmDepositorWallet",
              type: "address",
            },
            { internalType: "uint256", name: "newAmount", type: "uint256" },
          ],
          internalType: "struct Trading.SyncUpArguments[]",
          name: "_data",
          type: "tuple[]",
        },
      ],
      name: "syncUp",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [],
      name: "treasuryAddress",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "string", name: "_caip10Token", type: "string" },
        { internalType: "string", name: "_caip10WalletOrName", type: "string" },
        { internalType: "uint256", name: "_amount", type: "uint256" },
        {
          internalType: "enum Trading.ActionIs",
          name: "_action",
          type: "uint8",
        },
      ],
      name: "withdraw",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "string", name: "_caip10Token", type: "string" },
        { internalType: "string", name: "_caip10Wallet", type: "string" },
        { internalType: "uint256", name: "_amount", type: "uint256" },
        { internalType: "uint256", name: "_nonce", type: "uint256" },
        { internalType: "bytes", name: "_userSignature", type: "bytes" },
      ],
      name: "withdrawWithExecutor",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ],
} as const;
